name: flutter_application_11
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.4.0
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  get: ^4.7.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
